coding-blocks/codingblocks.online.projectx

app/pods/classroom/timeline/overview/template.hbs
app/pods/components/about-course/template.hbs

fixed ri-visit to re-visit

---

app/pods/components/nav-bar/template.hbs

fix #56 toggle nav-bar on clicking nav-links

---

app/helpers/format-price.js
app/pods/components/about-course/template.hbs
app/pods/components/recommended-courses/template.hbs
app/pods/courses/index/template.hbs
tests/integration/helpers/format-price-test.js

fixes #27 
I have also added '₹' symbol instead of 'Rs.' which was being used earlier, i hope it's okay.
Here's the screenshot from the build :-

fix price 0 as free

---

app/pods/components/notification-dropdown/component.js
app/pods/components/notification-dropdown/template.hbs

Show a lot of notifications at once

---

app/pods/components/carousel-cards/component.js
app/styles/objects/carousel/carousel.scss

Fixes #75 
@abhishek97 Please review.

Fixes Register button not visible for carousel cards after the 2nd card

---

app/pods/components/notification-dropdown/template.hbs
package.json

render notifications in markdown

---

app/pods/components/recommended-courses/component.js
app/pods/courses/index/route.js

Reverts coding-blocks/codingblocks.online.projectx#102

Revert "Sort the courses on the basis of difficulty"

---

app/pods/components/recommended-courses/component.js
app/pods/courses/index/route.js

Revert 104 revert 102 difficulty sort

---

app/pods/components/problem-statement-component/template.hbs

fixes #110 @abhishek97 Please review.

Render Problem Statement as Markdown

---

app/styles/objects/o-doubt/o-doubt.scss

fix overflow in doubts section

---

app/styles/elements/elements.card.mentors.scss
app/styles/elements/elements.card.price.scss
app/styles/elements/elements.card.text.scss
app/styles/elements/elements.icon.scss
app/styles/elements/elements.level.scss
app/styles/media-query/media.card.layout.scss
app/styles/media-query/media.course-progress/media.course-progress.scss
app/styles/objects/o-card-layout/card.scss
app/styles/objects/o-sidebar/o-sidebar.scss

Reverts coding-blocks/codingblocks.online.projectx#117
breaking difficulty level

Revert "Motley Pull"

---

app/pods/components/recommended-courses/template.hbs
app/pods/courses/index/template.hbs
app/styles/elements/elements.level.scss
app/styles/objects/o-card-layout/card.scss

@witty123  fixes #22 and https://github.com/coding-blocks/motley/issues/127. Please review

align center difficulty icon

---

app/pods/components/about-course/template.hbs

 Added content icons in course content page

---

app/pods/components/notification-dropdown/template.hbs

Notif icon bug fixed

---

app/pods/attempt/content/index/heading/template.hbs

CHange the sign in go to dashboard

---

app/pods/components/otp-enroll/component.js

Closes https://github.com/coding-blocks/codingblocks.online.projectx/issues/94

show error messages for Otp-enroll component

---

app/pods/attempt/content/index/heading/template.hbs
app/pods/classroom/timeline/template.hbs
app/pods/components/discourse-topics-view/template.hbs

closes #147 @abhishek97 Please check.

replaced Solve Your Doubts with Ask Your Doubts

---

app/pods/classroom/index/template.hbs
app/pods/classroom/timeline/template.hbs
app/pods/components/recommended-courses/template.hbs
app/pods/courses/index/template.hbs

@abhishek97 Please review. Closes #140

Hyperlinked Course Titles

---

app/pods/classroom/timeline/contents/template.hbs

Appropriate message in case there are no contents

---

app/helpers/embed.js

Added autoplay youtube 

---

app/pods/components/notification-dropdown/component.js

Fixes #132 .
Pinging @abhishek97

Closes notification box when clicked outside it.

---

app/pods/components/recommended-courses/component.js
app/pods/courses/index/route.js

Difficulty sort

---

app/pods/attempt/content/index/controller.js
app/pods/attempt/content/index/route.js
app/pods/attempt/content/route.js
app/pods/attempt/controller.js
app/pods/attempt/index/route.js
app/pods/attempt/route.js
app/pods/attempt/template.hbs
app/pods/classroom/timeline/contents/controller.js
app/pods/classroom/timeline/contents/template.hbs
app/pods/components/accordian-head/component.js

- Moves SectionId to QueryParam for `/attempt` and it's child routes.
- Render Accordion in the expanded state if appropriate.

Make SectionId route-able state.

---

app/pods/components/nav-bar/template.hbs

Navbar update

---

app/pods/404/template.hbs
app/pods/attempt/route.js
app/router.js
tests/unit/pods/404/route-test.js

Autocorrects the runAttemptId if wrong, Effectively allowing users to share link for course contents among other enrolled users.

Autocorrect run attempt

---

app/styles/_elements.scss
app/styles/_media-query.scss
app/styles/_objects.scss
app/styles/elements/elements.alert.scss
app/styles/elements/elements.modal.scss
app/styles/media-query/media.changdp.scss
app/styles/media-query/media.o-profile.card.edit.scss
app/styles/objects/o-about-course/o-buy-top.scss
app/styles/objects/o-changedp/o-changedp.scss
app/styles/objects/o-grid/grid/_variables.scss
app/styles/objects/o-modal/o-modal.scss
app/styles/objects/o-profile-page-edit/o-profile-page-edit.scss

fix: buy course stripe height

---

app/pods/attempt/template.hbs

Change x from table of contents

---

app/pods/classroom/timeline/overview/template.hbs
app/pods/components/about-course/template.hbs

render instructor description as markdown

---

app/models/course.js
app/pods/classroom/index/template.hbs
app/pods/classroom/timeline/template.hbs
app/pods/components/recommended-courses/template.hbs
app/pods/courses/id/route.js
app/pods/courses/index/template.hbs

- allows urls like `/courses/:slug` along with `/courses/:id`

allow slugs to be used as course identifier

---

app/pods/classroom/index/template.hbs

Show free trial if course is not premium

---

app/pods/classroom/index/template.hbs

Reverts coding-blocks/codingblocks.online.projectx#180 untill we fix data loading pattern.

Revert "Show free trial if course is not premium"

---

app/pods/classroom/index/template.hbs

Reverts coding-blocks/codingblocks.online.projectx#182

Redo: "Show free trial if course is not premium"

---

app/index.html
app/pods/components/nav-bar/template.hbs

Reverts coding-blocks/codingblocks.online.projectx#184
This changes for all the pages.

Revert "SEO improvements"

---

app/models/run.js
app/pods/components/about-course/template.hbs
app/pods/courses/index/route.js

Added discription in runs

---

app/pods/classroom/timeline/overview/template.hbs
app/pods/classroom/timeline/template.hbs
package-lock.json
package.json

Limit height of course's summary

---

app/pods/classroom/timeline/overview/template.hbs
app/pods/classroom/timeline/template.hbs
package-lock.json
package.json

add line-clamp

---

app/pods/components/nav-bar/template.hbs
app/pods/components/notification-dropdown/template.hbs
app/styles/elements/elements.notify-type.scss
app/styles/objects/o-nav-layout/o-nav-layout.scss
app/styles/objects/o-notification/o-notification.scss

Scale down

---

app/pods/components/about-course/template.hbs

added: mobile view for course review

---

app/pods/attempt/content/quiz/attempt/index/route.js

quiz_attempt.status==FINAL? redirect to qna

---

app/pods/components/about-course/template.hbs

fixes #238 @witty123  Please review

Replaced otp enroll with free trial

---

app/pods/components/hls-player/component.js

Fix for playback speed

---

app/index.html

conditional script of jivochat

---

app/index.html

Reverts coding-blocks/codingblocks.online.projectx#260

Revert "conditional script of jivochat"

---

app/pods/classroom/timeline/template.hbs

fixes #243 @witty123 @abhishek97

buy button and free trial

---

app/pods/components/about-course/template.hbs
app/pods/components/difficulty-dots/component.js
app/pods/components/difficulty-dots/template.hbs
app/pods/components/my-courses/component.js
app/pods/components/my-courses/template.hbs
app/pods/components/percent-complete/component.js
app/pods/components/percent-complete/template.hbs
app/pods/components/recommended-courses/component.js
app/pods/components/recommended-courses/template.hbs
app/pods/courses/index/template.hbs
package.json
tests/integration/pods/components/difficulty-dots/component-test.js

Add: new home cards

---

app/pods/components/my-courses/template.hbs
app/pods/components/nav-bar/template.hbs
package.json

added free-trial label

---

app/models/instructor.js
app/pods/classroom/timeline/overview/template.hbs
app/pods/components/about-course/template.hbs

Add: Instructor Email

---

app/pods/components/referral-code/component.js
app/pods/components/referral-code/template.hbs

Copy Referal Coupon on Click

---

app/pods/classroom/timeline/overview/template.hbs
app/pods/components/carousel-cards/component.js
app/pods/components/carousel-cards/template.hbs
package.json

added FAQs in classroom page

---

app/models/section.js
app/pods/attempt/template.hbs
app/pods/classroom/timeline/contents/template.hbs
app/pods/components/accordian-head/template.hbs

added section deadline to section

---

app/pods/components/about-course/component.js
app/pods/components/about-course/template.hbs
app/pods/components/review-carousel/component.js
app/pods/components/review-carousel/template.hbs
app/pods/courses/id/template.hbs
app/pods/courses/index/controller.js
app/pods/courses/index/route.js
tests/integration/pods/components/review-carousel/component-test.js

Course reviews

---

app/models/run-attempt.js
app/pods/classroom/timeline/template.hbs
app/pods/components/my-courses/template.hbs

fix: falsy batch-end date

---

app/pods/attempt/route.js
app/pods/components/code-editor/template.hbs
app/pods/components/player-code-challenge/template.hbs
package.json

- increased input-output section height
- reduced height of language selector

ide updates

---

app/pods/attempt/content/quiz/attempt/index/template.hbs
package.json

fix: quiz layout

---

package.json

motley: 0.3.30

---

app/pods/components/doubt-view-attempt/component.js
app/pods/components/doubt-view-attempt/template.hbs
app/pods/components/doubts-view/component.js
app/pods/components/doubts-view/template.hbs

err msg update in doubts section

---

app/pods/attempt/content/quiz/view/template.hbs

fix: quiz layout 2.0

---

app/pods/attempt/template.hbs
app/pods/classroom/timeline/contents/template.hbs

showing all contents

---

app/pods/components/my-courses/template.hbs
app/pods/components/run-request-button/component.js
app/pods/components/run-request-button/template.hbs

- show user message if not enrolled in any course
- redirect to course consumption page if runRequest is accepted

org update:

---

app/models/problem.js
app/pods/components/player-code-challenge/component.js
app/pods/components/player-code-challenge/template.hbs
app/pods/components/submissions-component/component.js

Ide update

---

app/pods/courses/index/template.hbs

Reverts coding-blocks/codingblocks.online.projectx#339

Revert "show strike through mrp in all courses"

---

app/pods/courses/index/template.hbs

Reverts coding-blocks/codingblocks.online.projectx#340

Revert "Revert "show strike through mrp in all courses""

---

app/pods/attempt/index/route.js

Check for next playable content

---

app/pods/components/about-course/component.js

Reverts coding-blocks/codingblocks.online.projectx#345

Revert "show batches of current course only"

---

app/pods/components/carousel-cards/template.hbs

carousel button-solid is button now

---

app/pods/components/dukaan-dropdown/component.js

divide price by 100

---

app/pods/components/recommended-courses/template.hbs
app/pods/courses/index/template.hbs
package.json
yarn.lock

motley 0.3.40

---

app/pods/components/about-course/template.hbs
app/pods/components/course-card/template.hbs
app/pods/components/recommended-courses/template.hbs
lib/hiring-blocks/addon/pods/listing/job/template.hbs

Markup fix

---

app/pods/components/testimonials-view/template.hbs
app/styles/app.scss
lib/hiring-blocks/addon/pods/components/success-stories/template.hbs

remove: "i was from" testimonials

---

app/pods/components/code-editor/template.hbs
app/styles/app.scss

fix: ide output pre tag overflow

---

app/pods/components/about-course/template.hbs

added: language in about-course

---

app/pods/components/about-course/template.hbs
app/styles/app.scss

* redirect to course overview page on preview

preview fix

---

lib/hiring-blocks/addon/pods/components/recommended-jobs/template.hbs

fix: view all jobs redirect

---

app/models/course.js
app/models/project.js
app/pods/components/about-course/template.hbs

added: projects to courses

---

app/pods/components/about-course/template.hbs

fix: space btw course-content & projects

---

app/models/application.js
lib/hiring-blocks/addon/pods/listing/job/controller.js
lib/hiring-blocks/addon/pods/listing/job/template.hbs
lib/hiring-blocks/package.json

Resume link

---

app/pods/components/loading-card-classroom/template.hbs
app/pods/components/loading-card/component.js
app/pods/components/loading-card/template.hbs
app/pods/components/my-courses/template.hbs
app/pods/components/recommended-courses/template.hbs
app/pods/courses/index-loading/template.hbs
tests/integration/pods/components/loading-card-classroom/component-test.js

update: skeleton card markup

---

lib/cricket-cup/addon/pods/components/cricket-match-card/component.js
lib/cricket-cup/addon/pods/index/route.js

livescore fix

---

package.json
yarn.lock

motley 0.3.46

---

lib/cricket-cup/addon/pods/components/result-view/component.js
lib/cricket-cup/addon/pods/components/result-view/template.hbs

earnings per match

---

app/pods/components/review-carousel/template.hbs
app/pods/index/template.hbs

* carousel-card in home page
* review-cards in about course page

overflow-fix

---

app/pods/components/player-csv-leaderboard/template.hbs
app/pods/components/player-csv/template.hbs
app/styles/app.scss

csv ui update

---

app/pods/components/nav-bar/template.hbs
app/router.js
package.json

Reverts coding-blocks/codingblocks.online.projectx#445

Revert "removing cricket cup"

---

app/pods/index/template.hbs
app/styles/app.scss

fix: pip in home webp

---

app/pods/components/code-editor/component.js
app/pods/components/player-code-challenge/component.js
app/pods/components/player-code-challenge/template.hbs

[FIX] persist code in IDE in case of WA

---

app/pods/components/player-code-challenge/component.js

Hb v2 run fix

---

app/pods/components/doubt-view-attempt/template.hbs

replaced input with textarea

---

app/pods/attempt/content/index/route.js
app/pods/components/player-code-challenge/component.js

fix: testcasaes now have dedicated endpoint

---

app/pods/classroom/timeline/template.hbs

No goodies for runs before october 18

---

app/pods/components/foot-er/template.hbs

updated terms&conditions and privacy policy links to open in new tab

---

app/pods/components/foot-er/template.hbs

updated social media links to open in new tab

---

app/pods/classroom/timeline/overview/template.hbs

Deadlines guideline updated

---

app/pods/components/otp-enroll/template.hbs

Reverts coding-blocks/codingblocks.online.projectx#482

Revert "#413"

---

app/pods/spin/index/controller.js
app/pods/spin/route.js

spin text and jivo fix

---

app/pods/components/spin/spin-winnings/template.hbs

winning card fix

---

app/initializers/authenticator.js
app/pods/spin/index/controller.js
app/pods/spin/index/template.hbs
app/services/current-user.js

verified emailis required to draw prizes

---

lib/ember-w-pack/addon/components/w-pagination.js
lib/ember-w-pack/addon/templates/components/w-pagination.hbs

[FIX] Conditionally disable pagination component

---

app/pods/spin/index/template.hbs

Last day to use

---

app/pods/index/template.hbs

This reverts commit d99f1a365859f109f0caac810e9d0f856172158a.

Revert "home spin"

---

app/models/submission.js
app/pods/attempt/content/code-challenge/route.js
app/pods/attempt/content/code-challenge/template.hbs
app/pods/components/code-challenge/code-challenge-result/code-challenge-result-error/template.hbs
app/pods/components/code-challenge/code-challenge-result/code-challenge-result-success/template.hbs
app/pods/components/code-challenge/code-challenge-result/code-challenge-result-testcases/template.hbs
app/pods/components/code-challenge/code-challenge-submission/component.js
app/pods/components/code-challenge/code-challenge-submission/template.hbs

Code challenge fix

---

app/pods/attempt/content/code-challenge/template.hbs
app/pods/components/code-challenge/code-challenge-code-editor/component.js
app/pods/components/code-challenge/code-challenge-code-editor/template.hbs
app/pods/components/code-challenge/code-challenge-result/code-challenge-result-testcases/template.hbs
app/pods/components/code-challenge/code-challenge-result/component.js

Progress fix

---

app/pods/attempt/content/template.hbs
app/pods/attempt/template.hbs
app/pods/components/player/player-doubts-tab/template.hbs
app/pods/components/tracks/tracks-course-row/template.hbs
app/pods/tracks/id/template.hbs
app/pods/tracks/index/template.hbs
lib/ember-w-pack/addon/templates/components/w-tab-nav.hbs

New track cards

---

app/pods/attempt/content/template.hbs
app/pods/attempt/template.hbs
app/pods/components/player/player-doubts-tab/template.hbs
app/pods/components/tracks/tracks-course-row/template.hbs
app/pods/tracks/id/template.hbs
app/pods/tracks/index/template.hbs
lib/ember-w-pack/addon/templates/components/w-tab-nav.hbs

Reverts coding-blocks/codingblocks.online.projectx#512

Revert "New track cards"

---

app/pods/components/code-challenge/code-challenge-code-editor/component.js
package.json
yarn.lock

base64 encoding fix

---

app/pods/classroom/timeline/index/template.hbs

goodie date update take #2

---

app/pods/attempt/template.hbs

scrollbar removed from content section

---

app/pods/components/nav-bar-public/component.js
app/pods/components/nav-bar-public/template.hbs
app/pods/components/nav-bar/component.js
app/pods/components/nav-bar/template.hbs

removed classroom from hamburger menu

removed classroom courses from hamburger menu

---

app/pods/components/side-nav/template.hbs

sidenav updated

---

app/pods/components/foot-er/template.hbs

Footer changes

---

app/pods/components/nav-bar/template.hbs
app/pods/components/tracks/tracks-doubts-form/component.js
app/pods/components/tracks/tracks-doubts-form/template.hbs

Reverts coding-blocks/codingblocks.online.projectx#530

Revert "Ashvary"

---

app/pods/components/code-challenge/code-challenge-code-editor/component.js

update fetch problem endpoint

---

app/pods/attempt/content/code-challenge/controller.js
app/pods/attempt/content/code-challenge/template.hbs
app/pods/attempt/content/template.hbs
app/pods/attempt/template.hbs
app/pods/components/code-challenge/code-challenge-code-editor/component.js
app/pods/components/code-challenge/code-challenge-code-editor/template.hbs
app/services/player.js
app/styles/app.scss
app/styles/components/code-challenge.scss
ember-cli-build.js
package.json
yarn.lock

- Introduce full screen mode for player content
- Basic support for code-challenge

Player fullscreen

---

app/pods/components/code-challenge/code-challenge-result/code-challenge-result-testcases/template.hbs
app/pods/components/code-challenge/code-challenge-result/component.js

update with new judge payload

---

app/models/course.js
app/models/run.js

Feat: add shift to run model and code to course model

---

config/environment.js
lib/hiring-blocks/addon/pods/components/job-listing-panels/job-list/component.js
lib/hiring-blocks/addon/pods/components/job-listing-panels/job-row/component.js
lib/hiring-blocks/addon/pods/components/job-listing-panels/job-row/template.hbs
lib/hiring-blocks/addon/pods/listing/index/template.hbs

use hiring api for job listing

---

lib/hiring-blocks/addon/pods/components/job-listing-panels/job-row/template.hbs

fix: jobs postedOn 50 years

---

app/pods/components/jobs-card/component.js
app/pods/components/jobs-card/template.hbs
app/pods/tracks/id/controller.js
lib/hiring-blocks/addon/pods/listing/job/route.js

jobs-card in tracks to hiringblocks

---

app/pods/classroom/timeline/index/template.hbs
app/pods/components/my-courses-list/recently-accessed/content/template.hbs

Signed-off-by: Arnav Gupta <arnav@codingblocks.com>

update pause text

---

app/pods/components/player/player-section-list-item/template.hbs

add markdown support in content title

---

app/pods/attempt/template.hbs
app/pods/components/about-course/template.hbs
app/pods/components/course-library/bookmarks/row/template.hbs
app/pods/components/course-library/notes/row/template.hbs
app/pods/components/doubt-view-attempt/template.hbs
app/pods/components/note-view/template.hbs
app/pods/components/player/player-header/template.hbs
app/pods/components/player/player-notes-list-item/template.hbs

content title is now markdown

---

app/pods/attempt/template.hbs
app/pods/components/about-course/template.hbs
app/pods/components/course-library/bookmarks/row/template.hbs
app/pods/components/course-library/notes/row/template.hbs
app/pods/components/doubt-view-attempt/template.hbs
app/pods/components/note-view/template.hbs
app/pods/components/player/player-header/template.hbs
app/pods/components/player/player-notes-list-item/template.hbs

Reverts coding-blocks/codingblocks.online.projectx#578

Revert "content title is now markdown"

---

app/pods/tracks/index/route.js

make limit 10 for get tracks

---

app/pods/components/hackerblocks-stats/template.hbs

change title of hackerblocks stats

---

app/pods/courses/route.js

Reverts coding-blocks/codingblocks.online.projectx#552

Revert "redirect nonNoagarro to /courses from /app/courses"

---

app/pods/spin/index/template.hbs

Bye Bye Spin-n-Win 2.0

---

app/pods/classroom/timeline/index/template.hbs
app/pods/components/blockers/upgrade/template.hbs
app/pods/components/carousel-cards/template.hbs
app/pods/components/certificate-comp/template.hbs
app/pods/components/code-challenge/code-challenge-code-editor/template.hbs
app/pods/components/dashboard/dashboard-applied-jobs/template.hbs
app/pods/components/dashboard/dashboard-wish-list/template.hbs
app/pods/components/extensions-widget/template.hbs
app/pods/components/hackerblocks-stats/template.hbs
app/pods/components/jobs-card/template.hbs
app/pods/components/mentor-card/template.hbs
app/pods/components/my-courses-list/course-row/template.hbs
app/pods/components/my-courses-list/run-row/template.hbs
app/pods/components/my-courses-list/wishlisted-courses/template.hbs
app/pods/components/nav-bar-public/template.hbs
app/pods/components/nav-bar/template.hbs
app/pods/components/otp-enroll/template.hbs
app/pods/components/performance-stats-view/template.hbs
app/pods/components/player/player-notes-tab/template.hbs
app/pods/components/rating-stars-static/template.hbs
app/pods/components/tracks/tracks-course-row/template.hbs
app/pods/components/tracks/tracks-doubts-form/template.hbs
app/pods/dashboard/template.hbs
app/pods/tracks/id/template.hbs
app/pods/tracks/index/template.hbs
package.json
yarn.lock

Ui updates

---

app/pods/attempt/content/code-challenge/template.hbs

fix: leaderboard not invalidating

---

app/pods/components/side-nav/template.hbs
app/pods/dashboard/controller.js
app/pods/dashboard/template.hbs

Hackerblocks card kinda feels odd as it is not aligned to continue learning card. Can we have heading on top of it? @abhishek97 @hitesshbajaj

revamp org dashboard view

---

app/pods/application/template.hbs
app/pods/components/about-course/template.hbs
app/pods/components/all-courses/template.hbs
app/pods/components/nav-bar/template.hbs
app/pods/components/recommended-courses/template.hbs

strip: remove certaing views for orgs

---

app/pods/components/course-card/component.js
app/pods/components/course-card/template.hbs

fix org view in course card

---

app/pods/components/discordinator-join-button/component.js

add redirectTo param in discordinator

---

app/pods/components/side-nav/template.hbs

add: cricket cup route in side-nav

---

app/pods/components/side-nav/template.hbs

removee cricket cup from org pages

---

app/models/progress.js

remove case of qna in progress

---

app/models/run-attempt.js

allow live batches to pause the run attempt

---

app/utils/browser.js

fix: dev setup when using host with a port

---

app/pods/components/side-nav/template.hbs

add: cricket-cup to side--nav

---

app/pods/components/player/player-doubts-list-item/template.hbs

fix: No replies Yet

---

app/pods/attempt/index/route.js
app/pods/classroom/timeline/library/controller.js
app/pods/classroom/timeline/library/template.hbs
app/pods/components/course-library/doubts/template.hbs
app/pods/components/player/player-doubts-list-item/template.hbs
app/pods/components/player/player-doubts-list/template.hbs

goto button from doubts
